Get http://localhost:3000/users

### 

POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user2",
    "password": "password1"
}